### ISSUE TITLE
Função de retorno de apontamentos

### ISSUE THREAD

**Issue by taniacruzz** [projetoKhali/API2Semestre#18]
# Descrição breve <br>
 - Criar função que irá retornar os apontamentos relevantes para aquele usuário. Para o colaborador, serão os apontamentos feitos por ele; para o gestor, serão os apontamentos feitos por ele e os apontamentos da(s) squad(s) que ele participa. Para o adm serão os apontamentos de todos os colaboradores. 
<br>

# Escopo 

- [x] Back-End  
- [ ] Front-End  
- [ ] Documentação  

# Sugestões  <br>
 - 
<br>

**Comment by JhonatanLop** [comment]
foi criado o método que retorna os apontamentos feitos pelo usuário.
o método recebe como parâmetro o objeto conexão e o id do usuário que será feita a pesquisa.
