### ISSUE TITLE
Diagrama com cardinalidade

### ISSUE THREAD

**Issue by taniacruzz** [projetoKhali/API2Semestre#26]
# Descrição breve <br>
 - Fazer Diagrama com entidades, relacionamentos e cardinalidade.
<br>

# Escopo 

- [ ] Back-End  
- [ ] Front-End  
- [x] Documentação  

# Sugestões  <br>
 - 
<br>

**Comment by paulo-granthon** [comment]
[Opção A](https://app.brmodeloweb.com/#!/conceptual/64238a79f231a44cf8c8601a) - Com distinção de entidades Administrador. Gestor e Colaborador em relação a Usuário.  

[Opção B](https://app.brmodeloweb.com/#!/conceptual/6424c31503f1b3b0a08de573) - Sem distinção de entidades por tipo de Usuário.
