### ISSUE TITLE
Criação do ERP do Banco de Dados

### ISSUE THREAD

**Issue by taniacruzz** [projetoKhali/API2Semestre#5]
Iniciar a modelagem de banco de dados, identificando quais serão as entidades, os dados necessários para seu cadastro no sistema e de que maneira cada entidade se relaciona. Serão no mínimo 6 tabelas relacionadas entre si.

**Comment by JhonatanLop** [comment]
[Diagrama - Banco de Dados para Apontamento de Horas V4.pdf](https://github.com/projetoKhali/API2Semestre/files/10952552/Diagrama.-.Banco.de.Dados.para.Apontamento.de.Horas.V4.pdf)

Diagrama das tabelas

**Comment by JhonatanLop** [comment]
![Diagrama - Banco de Dados para Apontamento de Horas](https://user-images.githubusercontent.com/111443621/225487063-fc4a064e-cba4-4a0e-a1c6-93268773b579.png)

**Comment by JhonatanLop** [comment]
![Diagrama](https://user-images.githubusercontent.com/111443621/225766813-dec51fd0-0cfc-4813-ab26-9ce53b85e894.png)

**Comment by JhonatanLop** [comment]
![Image](https://user-images.githubusercontent.com/111443621/227329421-16c01592-985c-4fa7-ade7-8a58b11f0d01.png)

Como conversado em sala de aula, a tabela "perfil" foi absorvida pela tabela "usuário", sendo substituída por um campo no lugar

**Comment by JhonatanLop** [comment]
V3 do gráfico


![Image](https://user-images.githubusercontent.com/111443621/227737584-ac2f6fa9-8f36-446e-aabc-50934353bc02.png)

**Comment by JhonatanLop** [comment]
visando a entrega de valor e a usabilidade do produto, a tabela de apontamento foi altera para absorver as tabelas "projeto" e "cliente" que passaram a ser um campo de texto da tabela "apontamento". as views também foram modificadas para se ajustar às mudanças

**Comment by JhonatanLop** [comment]
![Image](https://user-images.githubusercontent.com/111443621/229209379-2648f3a9-5f42-4521-95f2-abfbdb134594.png)

Atualização V3 do diagrama ERP

**Comment by JhonatanLop** [comment]
![Image](https://user-images.githubusercontent.com/111443621/229264562-f5a2e68c-1ce8-401a-b8e1-97d083a1ac69.png)

**Comment by JhonatanLop** [comment]
![Diagrama do banco de dados](https://user-images.githubusercontent.com/111443621/229374376-0243e7ee-ed4f-40a4-8f63-1688f1b6abce.png)

alterando nome da tabela de "aprovacao" -> "avaliacao"
